#!/usr/bin/perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
# Copyright 2017 Andrea Gomez <hi@daedra.ml>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 100%, 85%, 60%, 40%,
# 20% as well as the icons using FontAwesomeand.
#
# The urgency (exit code 33) is set if there is less that 5% remaining.

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $full_text;
my $short_text;
my $bat_number = $ENV{BLOCK_INSTANCE} || 0;

# Read the first line of the "acpi" command output
open (ACPI, "acpi -b | grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# Fail on unexpected output
if ($acpi !~ /: (\w+), (\d+)%/) {
    die "$acpi\n";
}

$status = $1;
$percent = $2;

# Display different icons for battery status
if ($status eq 'Discharging') {
    if ($percent < 20) {
        $full_text .= "\x{f244}";
    } elsif ($percent < 40) {
        $full_text .= "\x{f243}";
    } elsif ($percent < 60) {
        $full_text .= "\x{f242}";
    } elsif ($percent < 85) {
        $full_text .= "\x{f241}";
    } elsif ($percent <= 100) {
        $full_text .= "\x{f240}";
    }
} elsif ($status eq 'Charging') {
    $full_text .= "\x{f1e6}";
}

$short_text = $full_text;

if ($acpi =~ /(\d\d:\d\d):/) {
    $full_text .= " $percent%";
}

# Print text
print "$full_text\n";
print "$short_text\n";

# Use a different colour for battery status
if ($status eq 'Discharging') {
    if ($percent < 20) {
        print "#f77b71\n";
    } elsif ($percent < 40) {
        print "#ef6191\n";
    } elsif ($percent < 60) {
        print "#b967c7\n";
    } elsif ($percent < 85) {
        print "#7884cb\n";
    } elsif ($percent <= 100) {
        print "#4ec2f7\n";
    } elsif ($percent < 5) {
        exit(33);
    }
}

else {
    print "#ffb64c\n";
}

exit(0);
